// 3 series that do not share x positions; each line spans only its own points, and a 3-year span picks whole years as its tick unit
//
// GENERATED by tests/gen_visual.py -- the case is defined in tests/cases.typ
// and rendered by every backend; edit it there, not here.
#import "/tests/lib.typ": render-case, setup
#show: setup
#render-case("lilaq", "scale", "line-sparse")
