// 20 categories — the labels stop fitting the band and have to angle, each anchored by its end so it stays over its own bar
//
// GENERATED by tests/gen_visual.py -- the case is defined in tests/cases.typ
// and rendered by every backend; edit it there, not here.
#import "/tests/lib.typ": render-case, setup
#show: setup
#render-case("lilaq", "scale", "bar-20")
