// Amount plus unit USD makes core emit a currency format, so ticks read $2,500 — grouped, prefixed, and with no decimals because the values are whole
//
// GENERATED by tests/gen_visual.py -- the case is defined in tests/cases.typ
// and rendered by every backend; edit it there, not here.
#import "/tests/lib.typ": render-case, setup
#show: setup
#render-case("lilaq", "simple", "currency-zero")
