#!/usr/bin/env python3
"""Mirror the shared visual test suite onto a backend.

The cases live once in `tests/cases.typ`; every backend renders all of them.
This scaffolds `tests/<backend>/<group>/<case>/` for each, so adding a backend is one
command rather than a directory of hand-copied files, and adding a *case*
covers every backend at once.

Reference images are never written here — `tt update` is the only thing that
may write into `ref/`, and it has to be run deliberately so the pictures get
looked at.

    python tests/gen_visual.py lilaq            # scaffold missing tests
    python tests/gen_visual.py lilaq --check    # fail if any are missing (CI)
    python tests/gen_visual.py --list           # the case names

After scaffolding: `tt update <backend>` to make the references, then look at
them before committing.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PKG = HERE.parent
CASES = HERE / "cases.typ"

TEMPLATE = """\
// {why}
//
// GENERATED by tests/gen_visual.py -- the case is defined in tests/cases.typ
// and rendered by every backend; edit it there, not here.
#import "/tests/lib.typ": render-case, setup
#show: setup
#render-case("{backend}", "{group}", "{case}")
"""


def case_names() -> list[tuple[str, str]]:
    """Read the `(group, case)` pairs out of `cases.typ`.

    A small parse rather than an import: this runs before Typst does, and the
    file is machine-written enough that the keys are unambiguous.
    """
    src = CASES.read_text(encoding="utf-8")
    body = src[src.index("#let CASES = ("):]
    out: list[tuple[str, str]] = []
    group = None
    for line in body.splitlines():
        # Groups sit at two spaces, cases at four.
        m = re.match(r"^  ([a-z][a-z0-9-]*): \($", line)
        if m:
            group = m.group(1)
            continue
        m = re.match(r"^    ([a-z0-9][a-z0-9-]*): \($", line)
        if m and group:
            out.append((group, m.group(1)))
    return out


def case_why(name: str) -> str:
    """The one-line reason the case exists, for the generated test's header."""
    src = CASES.read_text(encoding="utf-8")
    m = re.search(rf"^    {re.escape(name)}: \(\n      why: (.+?)\n      [a-z.]", src, re.MULTILINE | re.DOTALL)
    if not m:
        return name
    parts = re.findall(r'"([^"]*)"', m.group(1))
    text = "".join(parts).strip()
    return text[:1].upper() + text[1:] if text else name


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("backend", nargs="?", help="backend to mirror the suite onto")
    ap.add_argument("--check", action="store_true", help="fail if any test is missing")
    ap.add_argument("--list", action="store_true", help="list the case names")
    args = ap.parse_args()

    names = case_names()
    if args.list:
        for group, n in names:
            print(f"  {group}/{n:20} {case_why(n)[:74]}")
        return 0
    if not args.backend:
        ap.error("a backend name is required (or --list)")

    missing: list[tuple[str, str]] = []
    for group, name in names:
        d = HERE / args.backend / group / name
        if (d / "test.typ").exists() and (d / "ref").exists():
            continue
        missing.append((group, name))

    if args.check:
        if missing:
            print(
                f"{len(missing)} case(s) not mirrored onto {args.backend}: "
                f"{', '.join(g + '/' + n for g, n in missing)}\n"
                f"run: python tests/gen_visual.py {args.backend}",
                file=sys.stderr,
            )
            return 1
        print(f"  all {len(names)} cases mirrored onto {args.backend}")
        return 0

    for group, name in missing:
        # `tt new --type persistent` is the only way to create a reference test;
        # `tt update` cannot promote a compile-only one.
        subprocess.run(
            ["tt", "new", "--type", "persistent", f"{args.backend}/{group}/{name}"],
            cwd=PKG, capture_output=True, check=True,
        )
    # Rewrite every test body, so an edit to a case propagates.
    for group, name in names:
        (HERE / args.backend / group / name / "test.typ").write_text(
            TEMPLATE.format(why=case_why(name), backend=args.backend, group=group, case=name),
            encoding="utf-8",
        )
    print(f"  {len(names)} cases mirrored onto {args.backend} ({len(missing)} new)")
    if missing:
        print(f"  now run: tt update {args.backend}   (and look at the pictures)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
