// Banded category axis; ticks read Jan/Feb/Mar although the rows are Mar/Jan/Feb; bars start at zero because a bar reads by length
//
// GENERATED by tests/gen_visual.py -- the case is defined in tests/cases.typ
// and rendered by every backend; edit it there, not here.
#import "/tests/lib.typ": render-case, setup
#show: setup
#render-case("lilaq", "simple", "bar")
