// GENERATED from flint/core/type_registry.py by test/gen_tables.py -- do not edit.
//
// Regenerate after any upstream change:  python test/gen_tables.py
// Check for drift in CI:                 python test/gen_tables.py --check
//
// Only pure-data tables are generated. Functions in this module are
// hand-ported and live alongside this file.

/// Every recognised semantic type, with its tier membership and the
/// orthogonal dimensions the compiler reads off it.
#let TYPE_REGISTRY = (
  DateTime: (
    t0: "Temporal",
    t1: "DateTime",
    visEncodings: ("temporal",),
    aggRole: "dimension",
    domainShape: "open",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
  Date: (
    t0: "Temporal",
    t1: "DateTime",
    visEncodings: ("temporal",),
    aggRole: "dimension",
    domainShape: "open",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
  Time: (
    t0: "Temporal",
    t1: "DateTime",
    visEncodings: ("temporal",),
    aggRole: "dimension",
    domainShape: "open",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
  Timestamp: (
    t0: "Temporal",
    t1: "DateTime",
    visEncodings: ("temporal",),
    aggRole: "dimension",
    domainShape: "open",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
  Year: (
    t0: "Temporal",
    t1: "DateGranule",
    visEncodings: ("temporal", "ordinal"),
    aggRole: "dimension",
    domainShape: "open",
    diverging: "none",
    formatClass: "integer",
    zeroBaseline: "arbitrary",
    zeroPad: 0.03,
  ),
  Quarter: (
    t0: "Temporal",
    t1: "DateGranule",
    visEncodings: ("ordinal",),
    aggRole: "dimension",
    domainShape: "cyclic",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
  Month: (
    t0: "Temporal",
    t1: "DateGranule",
    visEncodings: ("ordinal",),
    aggRole: "dimension",
    domainShape: "cyclic",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
  Week: (
    t0: "Temporal",
    t1: "DateGranule",
    visEncodings: ("ordinal",),
    aggRole: "dimension",
    domainShape: "cyclic",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
  Day: (
    t0: "Temporal",
    t1: "DateGranule",
    visEncodings: ("ordinal",),
    aggRole: "dimension",
    domainShape: "cyclic",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
  Hour: (
    t0: "Temporal",
    t1: "DateGranule",
    visEncodings: ("ordinal",),
    aggRole: "dimension",
    domainShape: "cyclic",
    diverging: "none",
    formatClass: "integer",
    zeroBaseline: "arbitrary",
    zeroPad: 0,
  ),
  YearMonth: (
    t0: "Temporal",
    t1: "DateGranule",
    visEncodings: ("temporal", "ordinal"),
    aggRole: "dimension",
    domainShape: "open",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
  YearQuarter: (
    t0: "Temporal",
    t1: "DateGranule",
    visEncodings: ("temporal", "ordinal"),
    aggRole: "dimension",
    domainShape: "open",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
  YearWeek: (
    t0: "Temporal",
    t1: "DateGranule",
    visEncodings: ("temporal", "ordinal"),
    aggRole: "dimension",
    domainShape: "open",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
  Decade: (
    t0: "Temporal",
    t1: "DateGranule",
    visEncodings: ("temporal", "ordinal"),
    aggRole: "dimension",
    domainShape: "open",
    diverging: "none",
    formatClass: "integer",
    zeroBaseline: "arbitrary",
    zeroPad: 0.03,
  ),
  Duration: (
    t0: "Temporal",
    t1: "Duration",
    visEncodings: ("quantitative",),
    aggRole: "additive",
    domainShape: "open",
    diverging: "none",
    formatClass: "unit-suffix",
    zeroBaseline: "meaningful",
    zeroPad: 0,
  ),
  Amount: (
    t0: "Measure",
    t1: "Amount",
    visEncodings: ("quantitative",),
    aggRole: "additive",
    domainShape: "open",
    diverging: "none",
    formatClass: "currency",
    zeroBaseline: "meaningful",
    zeroPad: 0,
  ),
  Price: (
    t0: "Measure",
    t1: "Amount",
    visEncodings: ("quantitative",),
    aggRole: "intensive",
    domainShape: "open",
    diverging: "none",
    formatClass: "currency",
    zeroBaseline: "meaningful",
    zeroPad: 0,
  ),
  Quantity: (
    t0: "Measure",
    t1: "Physical",
    visEncodings: ("quantitative",),
    aggRole: "additive",
    domainShape: "open",
    diverging: "none",
    formatClass: "unit-suffix",
    zeroBaseline: "meaningful",
    zeroPad: 0,
  ),
  Temperature: (
    t0: "Measure",
    t1: "Physical",
    visEncodings: ("quantitative",),
    aggRole: "intensive",
    domainShape: "open",
    diverging: "conditional",
    formatClass: "unit-suffix",
    zeroBaseline: "arbitrary",
    zeroPad: 0.05,
  ),
  Percentage: (
    t0: "Measure",
    t1: "Proportion",
    visEncodings: ("quantitative",),
    aggRole: "intensive",
    domainShape: "bounded",
    diverging: "none",
    formatClass: "percent",
    zeroBaseline: "contextual",
    zeroPad: 0,
  ),
  Profit: (
    t0: "Measure",
    t1: "SignedMeasure",
    visEncodings: ("quantitative",),
    aggRole: "signed-additive",
    domainShape: "open",
    diverging: "conditional",
    formatClass: "decimal",
    zeroBaseline: "meaningful",
    zeroPad: 0,
  ),
  PercentageChange: (
    t0: "Measure",
    t1: "SignedMeasure",
    visEncodings: ("quantitative",),
    aggRole: "intensive",
    domainShape: "open",
    diverging: "conditional",
    formatClass: "percent",
    zeroBaseline: "contextual",
    zeroPad: 0.05,
  ),
  Sentiment: (
    t0: "Measure",
    t1: "SignedMeasure",
    visEncodings: ("quantitative",),
    aggRole: "intensive",
    domainShape: "open",
    diverging: "inherent",
    formatClass: "decimal",
    zeroBaseline: "meaningful",
    zeroPad: 0,
  ),
  Correlation: (
    t0: "Measure",
    t1: "SignedMeasure",
    visEncodings: ("quantitative",),
    aggRole: "intensive",
    domainShape: "bounded",
    diverging: "inherent",
    formatClass: "decimal",
    zeroBaseline: "meaningful",
    zeroPad: 0,
  ),
  Count: (
    t0: "Measure",
    t1: "GenericMeasure",
    visEncodings: ("quantitative",),
    aggRole: "additive",
    domainShape: "open",
    diverging: "none",
    formatClass: "integer",
    zeroBaseline: "meaningful",
    zeroPad: 0,
  ),
  Number: (
    t0: "Measure",
    t1: "GenericMeasure",
    visEncodings: ("quantitative",),
    aggRole: "additive",
    domainShape: "open",
    diverging: "none",
    formatClass: "decimal",
    zeroBaseline: "meaningful",
    zeroPad: 0,
  ),
  Rank: (
    t0: "Discrete",
    t1: "Rank",
    visEncodings: ("ordinal",),
    aggRole: "dimension",
    domainShape: "open",
    diverging: "none",
    formatClass: "integer",
    zeroBaseline: "arbitrary",
    zeroPad: 0.08,
  ),
  Score: (
    t0: "Discrete",
    t1: "Score",
    visEncodings: ("quantitative", "ordinal"),
    aggRole: "intensive",
    domainShape: "bounded",
    diverging: "conditional",
    formatClass: "decimal",
    zeroBaseline: "contextual",
    zeroPad: 0.05,
  ),
  ID: (
    t0: "Identifier",
    t1: "ID",
    visEncodings: ("nominal",),
    aggRole: "identifier",
    domainShape: "open",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "arbitrary",
    zeroPad: 0,
  ),
  Latitude: (
    t0: "Geographic",
    t1: "GeoCoordinate",
    visEncodings: ("quantitative", "geographic"),
    aggRole: "dimension",
    domainShape: "fixed",
    diverging: "none",
    formatClass: "decimal",
    zeroBaseline: "arbitrary",
    zeroPad: 0.02,
  ),
  Longitude: (
    t0: "Geographic",
    t1: "GeoCoordinate",
    visEncodings: ("quantitative", "geographic"),
    aggRole: "dimension",
    domainShape: "fixed",
    diverging: "none",
    formatClass: "decimal",
    zeroBaseline: "arbitrary",
    zeroPad: 0.02,
  ),
  Country: (
    t0: "Geographic",
    t1: "GeoPlace",
    visEncodings: ("nominal",),
    aggRole: "dimension",
    domainShape: "open",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
  State: (
    t0: "Geographic",
    t1: "GeoPlace",
    visEncodings: ("nominal",),
    aggRole: "dimension",
    domainShape: "open",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
  City: (
    t0: "Geographic",
    t1: "GeoPlace",
    visEncodings: ("nominal",),
    aggRole: "dimension",
    domainShape: "open",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
  Region: (
    t0: "Geographic",
    t1: "GeoPlace",
    visEncodings: ("nominal",),
    aggRole: "dimension",
    domainShape: "open",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
  Address: (
    t0: "Geographic",
    t1: "GeoPlace",
    visEncodings: ("nominal",),
    aggRole: "dimension",
    domainShape: "open",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
  ZipCode: (
    t0: "Geographic",
    t1: "GeoPlace",
    visEncodings: ("nominal",),
    aggRole: "identifier",
    domainShape: "open",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
  Category: (
    t0: "Categorical",
    t1: "Entity",
    visEncodings: ("nominal",),
    aggRole: "dimension",
    domainShape: "open",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
  Name: (
    t0: "Categorical",
    t1: "Entity",
    visEncodings: ("nominal",),
    aggRole: "dimension",
    domainShape: "open",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
  Status: (
    t0: "Categorical",
    t1: "Coded",
    visEncodings: ("nominal",),
    aggRole: "dimension",
    domainShape: "open",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
  Boolean: (
    t0: "Categorical",
    t1: "Coded",
    visEncodings: ("nominal",),
    aggRole: "dimension",
    domainShape: "fixed",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
  Direction: (
    t0: "Categorical",
    t1: "Coded",
    visEncodings: ("ordinal", "nominal"),
    aggRole: "dimension",
    domainShape: "cyclic",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
  Range: (
    t0: "Categorical",
    t1: "Binned",
    visEncodings: ("ordinal",),
    aggRole: "dimension",
    domainShape: "open",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
  Unknown: (
    t0: "Categorical",
    t1: "Entity",
    visEncodings: ("nominal",),
    aggRole: "dimension",
    domainShape: "open",
    diverging: "none",
    formatClass: "plain",
    zeroBaseline: "none",
    zeroPad: 0,
  ),
)

/// Fallback entry for a semantic type not in the registry.
#let UNKNOWN_ENTRY = (
  t0: "Categorical",
  t1: "Entity",
  visEncodings: ("nominal",),
  aggRole: "dimension",
  domainShape: "open",
  diverging: "none",
  formatClass: "plain",
  zeroBaseline: "none",
  zeroPad: 0,
)
