// 200 points across 4 series on a temporal axis — ticks must fall on calendar boundaries (half-years here) rather than on sampled data points, and be labelled at the granularity of that boundary
//
// GENERATED by tests/gen_visual.py -- the case is defined in tests/cases.typ
// and rendered by every backend; edit it there, not here.
#import "/tests/lib.typ": render-case, setup
#show: setup
#render-case("lilaq", "scale", "line-200")
