// Temporal coordinates are epoch milliseconds; a 6-month span picks months as its tick unit, so every point gets a tick and none is invented between them
//
// GENERATED by tests/gen_visual.py -- the case is defined in tests/cases.typ
// and rendered by every backend; edit it there, not here.
#import "/tests/lib.typ": render-case, setup
#show: setup
#render-case("lilaq", "simple", "area-temporal")
