// A colour channel splits the rows into series; each line runs in x order rather than row order, and a line axis gets no band padding
//
// GENERATED by tests/gen_visual.py -- the case is defined in tests/cases.typ
// and rendered by every backend; edit it there, not here.
#import "/tests/lib.typ": render-case, setup
#show: setup
#render-case("lilaq", "simple", "line-series")
