// A category whose value is zero — a bar reads by length, so its axis stays pinned to the baseline and the empty bar sits on it rather than floating above a padded axis
//
// GENERATED by tests/gen_visual.py -- the case is defined in tests/cases.typ
// and rendered by every backend; edit it there, not here.
#import "/tests/lib.typ": render-case, setup
#show: setup
#render-case("lilaq", "simple", "bar-zero")
